[package]
name = "xenia"
version = "0.1.0"
edition = "2024_07"
license-file = "../LICENSE"

[dependencies]
starknet = "2.20.0"
openzeppelin = "3.0.0"

[dev-dependencies]
snforge_std = "0.63.0"
assert_macros = "2.20.0"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[features]
test_contracts = []

[scripts]
test = "snforge test --features test_contracts"

[[target.starknet-contract]]
sierra = true
casm = true

[[test]]
name = "xenia_unittest"
